### ISSUE TITLE
Add to flathub?

### ISSUE THREAD

**Issue by nedrichards** [frac-tion/teleport-flatpak#1]
Hey there, this looks pretty cool. [Flathub](https://flathub.org/) can easily host your app if you wish and give access to distribution, builds for x86 and ARM, free bandwidth etc. all whilst still being managed by you.

The only changes I can immediately see that [you'd have to make](https://github.com/flathub/flathub/wiki/Review-Guidelines) would be pointing to a release or git tag rather than just the latest commit, and removing the 'devel' bits but other than that it looks like you already comply with the rest of the review guidelines.

**Comment by bertob** [comment]
We're currently finalizing the initial release, we'll submit it to Flathub as soon as we have that ready.
